version: "3.7"

services:
  mongo:
    container_name: mex-db
    image: mongo    
    volumes:
      - db_volume:/data/db
    ports:
      - 27017:27017
  app:
    container_name: mex-back
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment: 
      - PORT=${PORT}
      - MONGO_URL=${MONGO_URL}
    ports: 
      - 3001:3001
    external_links: 
      - mongo  
    depends_on:
      - mongo  
volumes:
  db_volume: {}         